<?php

namespace Drupal\nishaj_exercise\Plugin\Block;

// Namespace where the block plugin class is located.
use Drupal\Core\Block\BlockBase;

// Imports the BlockBase class.
// Imports the FormStateInterface class.

/**
 * Provides simple block for d4drupal.
 *
 * @Block (
 * id = "nishaj_exercise",
 * admin_label = "Custom Plugin Block"
 * )
 */
class CustomBlock extends BlockBase {
  // Base which comes from the core.

  /**
   * {@inheritdoc}
   */
  public function build() {
    // Returns the rendered form generated by.
    // The CustomForm form class defined in the same module.
    // FormBuilder() service is used to get the form object and then calling.
    // The getForm() method with the fully-qualified
    // Name of CustomForm form class to build form.
    $form = \Drupal::formBuilder()->getForm('\Drupal\nishaj_exercise\Form\CustomConfigForm');
    // Mention the path here from where the file should get rendered.
    // Return function.
    return $form;
  }

}
